# Generated by Django 4.0.6 on 2022-08-03 09:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(default='', max_length=50, unique=True, verbose_name='email')),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'CompanyAdmin'), (3, 'CompanyManager')], default=1, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('has_vk', models.BooleanField()),
                ('has_fb', models.BooleanField()),
                ('has_google', models.BooleanField()),
                ('has_yandex', models.BooleanField()),
                ('has_myTarget', models.BooleanField()),
                ('has_tiktok', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('test_service_app_1.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Yandex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100, unique=True)),
                ('client_login', models.CharField(default='', max_length=50, unique=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='VK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100, unique=True)),
                ('version', models.CharField(default='', max_length=100, unique=True)),
                ('id_rk', models.CharField(default='', max_length=100, unique=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='TikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=100, unique=True)),
                ('refresh_token', models.CharField(default='', max_length=100, unique=True)),
                ('client_key', models.CharField(default='', max_length=100, unique=True)),
                ('client_secret', models.CharField(default='', max_length=100, unique=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='MyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mclient_id', models.CharField(default='', max_length=50, unique=True)),
                ('client_secret', models.CharField(default='', max_length=100, unique=True)),
                ('token', models.CharField(default='', max_length=100, unique=True)),
                ('refresh_token', models.CharField(default='', max_length=100, unique=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_token', models.CharField(default='', max_length=100, unique=True)),
                ('gclient_id', models.CharField(default='', max_length=50, unique=True)),
                ('client_secret', models.CharField(default='', max_length=50, unique=True)),
                ('refresh_token', models.CharField(default='', max_length=100, unique=True)),
                ('login_customer_id', models.CharField(default='', max_length=50, unique=True)),
                ('login', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=50, unique=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100, unique=True)),
                ('login', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=50, unique=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.client')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=255, verbose_name='Наименование организации')),
                ('fio_otvetst', models.CharField(default='', max_length=255, verbose_name='ФИО ответственного лица')),
                ('email_otvetst', models.EmailField(max_length=254, verbose_name='E-mail ответственного лица')),
                ('phone_otvetst', models.CharField(default='', max_length=255, verbose_name='Телефон ответственного лица')),
                ('business_id_number', models.IntegerField(default=0, verbose_name='БИН')),
                ('business_kpp', models.CharField(default='', max_length=255, verbose_name='КПП')),
                ('full_company_name', models.CharField(default='', max_length=255, verbose_name='Полное наименование организации')),
                ('post_index', models.IntegerField(default=0, verbose_name='Почтовый индекс')),
                ('street', models.CharField(default='', max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(default='', max_length=255, verbose_name='Номер дома')),
                ('building', models.CharField(default='', max_length=255, verbose_name='Корпус')),
                ('office_number', models.CharField(default='', max_length=255, verbose_name='Номер офиса')),
                ('bank_iik', models.CharField(default='', max_length=255, verbose_name='БИК')),
                ('raschet_schet', models.CharField(default='', max_length=255, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(default='', max_length=255, verbose_name='Название банка')),
                ('correspondent_account', models.CharField(default='', max_length=255, verbose_name='Корреспондентный счет')),
                ('company_admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.company'),
        ),
        migrations.CreateModel(
            name='CompanyManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('company_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_service_app_1.company', verbose_name='Рекламное агентство')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('test_service_app_1.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
