# Generated by Django 4.0.6 on 2022-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='has_fb',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_google',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_myTarget',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_tiktok',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_vk',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_yandex',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
