# Generated by Django 4.0.6 on 2022-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service_app_1', '0003_alter_user_position_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Назначение клиентов'),
        ),
    ]
